window.NirogyamProducts = [
  { id: 'nirothyro', name: 'NiroThyro', category: 'thyroid', price: 649, oldPrice: 899, rating: 4.5, count: 128, discount: '28% OFF', icon: 'fa-bolt', image: 'asets/img/nirothyro/main-nirothyro.jpeg', gallery: ['asets/img/nirothyro/main-nirothyro.jpeg', 'asets/img/nirothyro/2-nirothyro.jpeg', 'asets/img/nirothyro/3-nirothyro.jpeg', 'asets/img/nirothyro/4-nirothyro.jpeg'], short: 'Balances thyroid function and supports healthy metabolism.', tag: 'Thyroid Support', details: 'NiroThyro is crafted to support thyroid function, metabolism, and everyday energy with a focused Ayurvedic wellness blend.' },
  { id: 'niroheart', name: 'NiroHeart', category: 'heart', price: 749, oldPrice: 999, rating: 4.7, count: 214, discount: '25% OFF', icon: 'fa-heart-pulse', image: 'asets/img/niroheart/main-niroheart.jpeg', gallery: ['asets/img/niroheart/main-niroheart.jpeg', 'asets/img/niroheart/2-niroheart.jpeg', 'asets/img/niroheart/3-niroheart.jpeg', 'asets/img/niroheart/4-niroheart.jpeg'], short: 'Supports healthy circulation and cardiovascular wellness.', tag: 'Heart Care', details: 'NiroHeart supports healthy circulation and cardiovascular wellness as part of a balanced daily routine.' },
  { id: 'nirojoint', name: 'NiroJoint', category: 'joint', price: 599, oldPrice: 849, rating: 4.3, count: 98, discount: '29% OFF', icon: 'fa-bone', image: 'asets/img/nirojoint/main-nirojoint.jpeg', gallery: ['asets/img/nirojoint/main-nirojoint.jpeg', 'asets/img/nirojoint/2-nirojoint.jpeg', 'asets/img/nirojoint/3-nirojoint.jpeg', 'asets/img/nirojoint/4-nirojoint.jpeg'], short: 'Eases stiffness and supports joint flexibility.', tag: 'Joint Care', details: 'NiroJoint is designed to support joint comfort, mobility, and flexibility for active everyday living.' },
  { id: 'nirokidney', name: 'NiroKidney', category: 'kidney', price: 699, oldPrice: 949, rating: 4.6, count: 156, discount: '26% OFF', icon: 'fa-droplet', image: 'asets/img/nirokidney/main-nirokidney.jpeg', gallery: ['asets/img/nirokidney/main-nirokidney.jpeg', 'asets/img/nirokidney/2-nirokidney.jpeg', 'asets/img/nirokidney/3-nirokidney.jpeg', 'asets/img/nirokidney/4-nirokidney.jpeg'], short: 'Supports kidney function and natural detox.', tag: 'Kidney Detox', details: 'NiroKidney supports kidney wellness and natural detox pathways with a traditional herbal care approach.' },
  { id: 'niropcos-care', name: 'NiroPCOS Care', category: 'women', price: 799, oldPrice: 1099, rating: 4.8, count: 302, discount: '27% OFF', icon: 'fa-venus', image: 'asets/img/niropcos/main-niropcos.jpeg', gallery: ['asets/img/niropcos/main-niropcos.jpeg', 'asets/img/niropcos/2-niropcos.jpeg', 'asets/img/niropcos/3-niropcos.jpeg', 'asets/img/niropcos/4-niropcos.jpeg'], short: 'Helps restore hormonal balance for PCOS/PCOD.', tag: 'Women Health', details: 'NiroPCOS Care supports women health and hormonal balance with Ayurvedic ingredients selected for daily wellness.' },
  { id: 'niropile', name: 'NiroPile', category: 'digestive', price: 549, oldPrice: 799, rating: 4.2, count: 76, discount: '31% OFF', icon: 'fa-band-aid', image: 'asets/img/niropile/main-niropile.jpeg', gallery: ['asets/img/niropile/main-niropile.jpeg', 'asets/img/niropile/2-niropile.jpeg', 'asets/img/niropile/3-niropile.jpeg', 'asets/img/niropile/4-niropile.jpeg'], short: 'Relief and digestive comfort for piles.', tag: 'Digestive Care', details: 'NiroPile is made to support digestive comfort and relief-focused daily care.' },
  { id: 'nirostamina', name: 'NiroStamina', category: 'energy', price: 699, oldPrice: 949, rating: 4.4, count: 189, discount: '26% OFF', icon: 'fa-bolt-lightning', image: 'asets/img/nirostamina/main-nirostamina.jpeg', gallery: ['asets/img/nirostamina/main-nirostamina.jpeg', 'asets/img/nirostamina/2-nirostamina.jpeg', 'asets/img/nirostamina/3-nirostamina.jpeg', 'asets/img/nirostamina/4-nirostamina.jpeg'], short: 'Boosts energy, vitality and everyday endurance.', tag: 'Energy Support', details: 'NiroStamina supports vitality, stamina, and everyday endurance with a natural wellness formulation.' },
  { id: 'nirosugar', name: 'NiroSugar', category: 'sugar', price: 749, oldPrice: 999, rating: 4.6, count: 143, discount: '25% OFF', icon: 'fa-vial', image: 'asets/img/nirosugar/main-nirosugar.jpeg', gallery: ['asets/img/nirosugar/main-nirosugar.jpeg', 'asets/img/nirosugar/2-nirosugar.jpeg', 'asets/img/nirosugar/3-nirosugar.jpeg', 'asets/img/nirosugar/4-nirosugar.jpeg'], short: 'Supports healthy, balanced blood sugar levels.', tag: 'Blood Sugar', details: 'NiroSugar supports balanced blood sugar wellness as part of a healthy diet and lifestyle.' },
  { id: 'nova-plus', name: 'Nova Plus', category: 'energy', price: 2499, oldPrice: 2999, rating: 4.9, count: 327, discount: '17% OFF', icon: 'fa-leaf', image: 'asets/img/niroplus/main-niroplus.jpeg', gallery: ['asets/img/niroplus/main-niroplus.jpeg', 'asets/img/niroplus/3-niroplus.jpeg', 'asets/img/niroplus/4-niroplus.jpeg'], short: 'A 28-herb infusion for energy, immunity, digestion and everyday wellness.', tag: 'Herbal Infusion', details: 'Nova Plus is a distinctive herbal infusion featuring a carefully curated blend of 28 herbs. This expertly crafted fusion delivers a refreshing and invigorating experience with each sip.' }
];

window.NirogyamProductUtils = {
  productUrl: function (product) {
    return 'nova-plus.html?product=' + encodeURIComponent(product.id);
  },
  find: function (id) {
    var products = window.NirogyamProducts || [];
    return products.find(function (product) { return product.id === id; }) || products.find(function (product) { return product.id === 'nova-plus'; }) || products[0];
  },
  money: function (amount) {
    return '&#8377;' + amount;
  }
};
